import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { ThrottlerModule } from '@nestjs/throttler';
import request from 'supertest';
import type { App } from 'supertest/types';
import { UserRole } from '../common/constants/index.js';
import { JwtAuthGuard } from '../common/guards/jwt-auth.guard.js';
import { RolesGuard } from '../common/guards/roles.guard.js';
import { SymptomCheckinsController } from './symptom-checkins.controller.js';
import { SymptomCheckinsService } from './symptom-checkins.service.js';

describe('SymptomCheckinsController', () => {
  it('configures the create endpoint rate limit', () => {
    // Metadata belongs to the method function generated by the decorator.
    // eslint-disable-next-line @typescript-eslint/unbound-method
    const handler = SymptomCheckinsController.prototype.create;

    expect(Reflect.getMetadata('THROTTLER:LIMITdefault', handler)).toBe(10);
    expect(Reflect.getMetadata('THROTTLER:TTLdefault', handler)).toBe(60000);
  });

  it('rejects the eleventh create request inside one minute', async () => {
    const symptomCheckinsService = {
      create: jest.fn().mockResolvedValue({ status: 'processing' }),
    };
    const moduleRef = await Test.createTestingModule({
      imports: [
        ThrottlerModule.forRoot({
          throttlers: [{ limit: 30, ttl: 60000 }],
        }),
      ],
      controllers: [SymptomCheckinsController],
      providers: [
        {
          provide: SymptomCheckinsService,
          useValue: symptomCheckinsService,
        },
      ],
    })
      .overrideGuard(JwtAuthGuard)
      .useValue({
        canActivate: (context: {
          switchToHttp: () => { getRequest: () => Record<string, unknown> };
        }) => {
          context.switchToHttp().getRequest().user = {
            id: '11111111-1111-4111-8111-111111111111',
            role: UserRole.IBU_HAMIL,
            puskesmas_id: null,
          };
          return true;
        },
      })
      .overrideGuard(RolesGuard)
      .useValue({ canActivate: () => true })
      .compile();
    const app: INestApplication<App> = moduleRef.createNestApplication();
    await app.init();

    try {
      const body = {
        pregnancy_profile_id: '22222222-2222-4222-8222-222222222222',
        checkin_type: 'pregnancy',
        answers: { sakit_kepala: false },
      };

      for (let attempt = 0; attempt < 10; attempt += 1) {
        await request(app.getHttpServer())
          .post('/symptom-checkins')
          .send(body)
          .expect(201);
      }

      await request(app.getHttpServer())
        .post('/symptom-checkins')
        .send(body)
        .expect(429);
      expect(symptomCheckinsService.create).toHaveBeenCalledTimes(10);
    } finally {
      await app.close();
    }
  });
});
